src/Entity/Oferta.php
<?php

namespace App\Entity;

use App\Repository\OfertaRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OfertaRepository::class)
 */
class Oferta
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $empresa_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titol;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $descripcio;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $data_publicacio;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ubicacio;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $estat;

    /**
     * @ORM\Column(type="integer")
     */
    private $categoria_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmpresaId(): ?int
    {
        return $this->empresa_id;
    }

    public function setEmpresaId(int $empresa_id): self
    {
        $this->empresa_id = $empresa_id;

        return $this;
    }

    public function getTitol(): ?string
    {
        return $this->titol;
    }

    public function setTitol(string $titol): self
    {
        $this->titol = $titol;

        return $this;
    }

    public function getDescripcio(): ?string
    {
        return $this->descripcio;
    }

    public function setDescripcio(string $descripcio): self
    {
        $this->descripcio = $descripcio;

        return $this;
    }

    public function getDataPublicacio(): ?string
    {
        return $this->data_publicacio;
    }

    public function setDataPublicacio($data_publicacio): self
    {
        $this->data_publicacio = $data_publicacio;

        return $this;
    }

    public function getUbicacio(): ?string
    {
        return $this->ubicacio;
    }

    public function setUbicacio(string $ubicacio): self
    {
        $this->ubicacio = $ubicacio;

        return $this;
    }

    public function getEstat(): ?string
    {
        return $this->estat;
    }

    public function setEstat(string $estat): self
    {
        $this->estat = $estat;

        return $this;
    }

    public function getCategoriaId(): ?int
    {
        return $this->categoria_id;
    }

    public function setCategoriaId(int $categoria_id): self
    {
        $this->categoria_id = $categoria_id;

        return $this;
    }
}

src/Form/OfertaType.php
<?php

namespace App\Form;

use App\Entity\Oferta;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Entity\Categoria;

use Symfony\Component\Form\Extension\Core\Type\TextType;

class OfertaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $categoria = new Categoria();
        $builder
            // ->add('empresa_id')
            ->add('titol', TextType::class, [
                'attr' => [
                    'placeholder' => 'Titol',
                    'class' => 'form-control'
                ]
            ])
            ->add('descripcio')
            // ->add('data_publicacio')
            ->add('ubicacio')
            // ->add('estat')
            ->add('categoria_id');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Oferta::class,
        ]);
    }
}

src/Controller/OfertaController.php
<?php

namespace App\Controller;

use App\Entity\Oferta;
use App\Form\OfertaType;
use App\Repository\OfertaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use DateTimeInterface;

/**
 * @Route("/oferta")
 */
class OfertaController extends AbstractController
{
    /**
     * @Route("/", name="oferta_index", methods={"GET"})
     */
    public function index(OfertaRepository $ofertaRepository): Response
    {
        return $this->render('oferta/index.html.twig', [
            'ofertas' => $ofertaRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="oferta_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $ofertum = new Oferta();
        // MAS ENDAVANT CAMBIAR PER EL REAL
        $ofertum->setEmpresaId(1);

        $date = date("Y-m-d");
        $ofertum->setDataPublicacio($date);
        
        $ofertum->setEstat("esborrany");
        $form = $this->createForm(OfertaType::class, $ofertum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ofertum);
            $entityManager->flush();

            return $this->redirectToRoute('oferta_index');
        }

        return $this->render('oferta/new.html.twig', [
            'ofertum' => $ofertum,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="oferta_show", methods={"GET"})
     */
    public function show(Oferta $ofertum): Response
    {
        return $this->render('oferta/show.html.twig', [
            'ofertum' => $ofertum,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="oferta_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Oferta $ofertum): Response
    {
        $form = $this->createForm(OfertaType::class, $ofertum);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('oferta_index');
        }

        return $this->render('oferta/edit.html.twig', [
            'ofertum' => $ofertum,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="oferta_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Oferta $ofertum): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ofertum->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ofertum);
            $entityManager->flush();
        }

        return $this->redirectToRoute('oferta_index');
    }
}

templates/oferta/_delete_form.html.twig
<form method="post" action="{{ path('oferta_delete', {'id': ofertum.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ofertum.id) }}">
    <button class="btn">Delete</button>
</form>

templates/oferta/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/oferta/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Oferta{% endblock %}

{% block body %}
    <h1>Edit Oferta</h1>

    {{ include('oferta/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('oferta_index') }}">back to list</a>

    {{ include('oferta/_delete_form.html.twig') }}
{% endblock %}

templates/oferta/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Oferta index{% endblock %}

{% block body %}
    <h1>Oferta index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Empresa_id</th>
                <th>Titol</th>
                <th>Descripcio</th>
                <th>Data_publicacio</th>
                <th>Ubicacio</th>
                <th>Estat</th>
                <th>Categoria_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ofertum in ofertas %}
            <tr>
                <td>{{ ofertum.id }}</td>
                <td>{{ ofertum.empresaId }}</td>
                <td>{{ ofertum.titol }}</td>
                <td>{{ ofertum.descripcio }}</td>
                <td>{{ ofertum.dataPublicacio ? ofertum.dataPublicacio|date('Y-m-d') : '' }}</td>
                <td>{{ ofertum.ubicacio }}</td>
                <td>{{ ofertum.estat }}</td>
                <td>{{ ofertum.categoriaId }}</td>
                <td>
                    <a href="{{ path('oferta_show', {'id': ofertum.id}) }}">show</a>
                    <a href="{{ path('oferta_edit', {'id': ofertum.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('oferta_new') }}">Create new</a>
{% endblock %}

templates/oferta/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Oferta{% endblock %}

{% block body %}
    <h1>Create new Oferta</h1>
    
    {{ include('oferta/_form.html.twig') }}

    <a href="{{ path('oferta_index') }}">back to list</a>
{% endblock %}

templates/oferta/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Oferta{% endblock %}

{% block body %}
    <h1>Oferta</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ofertum.id }}</td>
            </tr>
            <tr>
                <th>Empresa_id</th>
                <td>{{ ofertum.empresaId }}</td>
            </tr>
            <tr>
                <th>Titol</th>
                <td>{{ ofertum.titol }}</td>
            </tr>
            <tr>
                <th>Descripcio</th>
                <td>{{ ofertum.descripcio }}</td>
            </tr>
            <tr>
                <th>Data_publicacio</th>
                <td>{{ ofertum.dataPublicacio ? ofertum.dataPublicacio|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Ubicacio</th>
                <td>{{ ofertum.ubicacio }}</td>
            </tr>
            <tr>
                <th>Estat</th>
                <td>{{ ofertum.estat }}</td>
            </tr>
            <tr>
                <th>Categoria_id</th>
                <td>{{ ofertum.categoriaId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('oferta_index') }}">back to list</a>

    <a href="{{ path('oferta_edit', {'id': ofertum.id}) }}">edit</a>

    {{ include('oferta/_delete_form.html.twig') }}
{% endblock %}