src/Entity/Candidat.php
<?php

namespace App\Entity;

use App\Repository\CandidatRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CandidatRepository::class)
 */
class Candidat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $usuari_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cognom1;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cognom2;

    /**
     * @ORM\Column(type="integer")
     */
    private $telefon;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsuariId(): ?int
    {
        return $this->usuari_id;
    }

    public function setUsuariId(int $usuari_id): self
    {
        $this->usuari_id = $usuari_id;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCognom1(): ?string
    {
        return $this->cognom1;
    }

    public function setCognom1(string $cognom1): self
    {
        $this->cognom1 = $cognom1;

        return $this;
    }

    public function getCognom2(): ?string
    {
        return $this->cognom2;
    }

    public function setCognom2(string $cognom2): self
    {
        $this->cognom2 = $cognom2;

        return $this;
    }

    public function getTelefon(): ?int
    {
        return $this->telefon;
    }

    public function setTelefon(int $telefon): self
    {
        $this->telefon = $telefon;

        return $this;
    }
}

src/Form/CandidatType.php
<?php

namespace App\Form;

use App\Entity\Candidat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CandidatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('usuari_id')
            ->add('nom')
            ->add('cognom1')
            ->add('cognom2')
            ->add('telefon')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Candidat::class,
        ]);
    }
}

src/Controller/CandidatController.php
<?php

namespace App\Controller;

use App\Entity\Candidat;
use App\Form\CandidatType;
use App\Repository\CandidatRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/candidat")
 */
class CandidatController extends AbstractController
{
    /**
     * @Route("/", name="candidat_index", methods={"GET"})
     */
    public function index(CandidatRepository $candidatRepository): Response
    {
        return $this->render('candidat/index.html.twig', [
            'candidats' => $candidatRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="candidat_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $candidat = new Candidat();
        $form = $this->createForm(CandidatType::class, $candidat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($candidat);
            $entityManager->flush();

            return $this->redirectToRoute('candidat_index');
        }

        return $this->render('candidat/new.html.twig', [
            'candidat' => $candidat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="candidat_show", methods={"GET"})
     */
    public function show(Candidat $candidat): Response
    {
        return $this->render('candidat/show.html.twig', [
            'candidat' => $candidat,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="candidat_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Candidat $candidat): Response
    {
        $form = $this->createForm(CandidatType::class, $candidat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('candidat_index');
        }

        return $this->render('candidat/edit.html.twig', [
            'candidat' => $candidat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="candidat_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Candidat $candidat): Response
    {
        if ($this->isCsrfTokenValid('delete'.$candidat->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($candidat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('candidat_index');
    }
}

templates/candidat/_delete_form.html.twig
<form method="post" action="{{ path('candidat_delete', {'id': candidat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ candidat.id) }}">
    <button class="btn">Delete</button>
</form>

templates/candidat/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/candidat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Candidat{% endblock %}

{% block body %}
    <h1>Edit Candidat</h1>

    {{ include('candidat/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('candidat_index') }}">back to list</a>

    {{ include('candidat/_delete_form.html.twig') }}
{% endblock %}

templates/candidat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidat index{% endblock %}

{% block body %}
    <h1>Candidat index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Usuari_id</th>
                <th>Nom</th>
                <th>Cognom1</th>
                <th>Cognom2</th>
                <th>Telefon</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for candidat in candidats %}
            <tr>
                <td>{{ candidat.id }}</td>
                <td>{{ candidat.usuariId }}</td>
                <td>{{ candidat.nom }}</td>
                <td>{{ candidat.cognom1 }}</td>
                <td>{{ candidat.cognom2 }}</td>
                <td>{{ candidat.telefon }}</td>
                <td>
                    <a href="{{ path('candidat_show', {'id': candidat.id}) }}">show</a>
                    <a href="{{ path('candidat_edit', {'id': candidat.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('candidat_new') }}">Create new</a>
{% endblock %}

templates/candidat/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Candidat{% endblock %}

{% block body %}
    <h1>Create new Candidat</h1>

    {{ include('candidat/_form.html.twig') }}

    <a href="{{ path('candidat_index') }}">back to list</a>
{% endblock %}

templates/candidat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidat{% endblock %}

{% block body %}
    <h1>Candidat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ candidat.id }}</td>
            </tr>
            <tr>
                <th>Usuari_id</th>
                <td>{{ candidat.usuariId }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ candidat.nom }}</td>
            </tr>
            <tr>
                <th>Cognom1</th>
                <td>{{ candidat.cognom1 }}</td>
            </tr>
            <tr>
                <th>Cognom2</th>
                <td>{{ candidat.cognom2 }}</td>
            </tr>
            <tr>
                <th>Telefon</th>
                <td>{{ candidat.telefon }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('candidat_index') }}">back to list</a>

    <a href="{{ path('candidat_edit', {'id': candidat.id}) }}">edit</a>

    {{ include('candidat/_delete_form.html.twig') }}
{% endblock %}